development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ripley_development
  pool: 5
  username: atpa
  password: C0wabunga 
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ripley_test
  pool: 5
  username: atpa 
  password: C0wabunga 

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ripley_production
  pool: 5
  username: atpa 
  password: C0wabunga

