development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rip_development
  pool: 5
  username: atpa
  password: ATPAatpa12345678$ 
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rip_test
  pool: 5
  username: atpa 
  password: ATPAatpa12345678$

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rip_production
  pool: 5
  username: atpa 
  password: ATPAatpa12345678$

