development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: rip_development
  pool: 5
  username: mgough
  password: changeme 
test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: rip_test
  pool: 5
  username: mgough 
  password: changeme

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: rip_development
  pool: 5
  username: mgough 
  password: changeme

