class CreateRecords < ActiveRecord::Migration[5.0]
  def change
    create_table :records do |t|

        t.string   "documentstatus"
        t.string   "filetype"
        t.string   "boxdesc1"
        t.string   "pagecount"
        t.string   "documentpath"
        t.string   "documentid"
        t.string   "boxdesc2"
        t.string   "employernumber"
        t.string   "batchid"
        t.string   "filedesc1"
        t.string   "filestatus"
        t.string   "filedesc2"
        t.string   "employername"
        t.string   "boxretentiondate"
        t.string   "dsfile"
        t.string   "account"
        t.string   "documentdesc1"
        t.string   "workorder"
        t.string   "migrated"
        t.string   "documentdesc2"
        t.string   "boxstatus"
        t.string   "pickupdate"
        t.string   "dsbox"
        t.string   "document"
        t.string   "scandate"
        t.string   "documenttype"
        t.string   "fileretentiondate"
        t.string   "documentretentiondate"
        t.string   "boxlocation"
        t.string   "filehash"
        t.string   "cisfile"
        t.string   "name"
        t.string   "ssn"
        t.string   "id2"
        t.string   "ocrpath"
        t.string   "docid"
        t.string   "database"
        t.string   "cisbox"
        t.string   "documentretetiondate"
        t.string   "fileid"
        t.string   "toboxdesc"
        t.string   "fromboxdesc"
        t.string   "employercity"
        t.string   "employerdate"
        t.string   "version4notsupported"
        t.string   "batchdate"
        t.string   "batchnumber"
        t.string   "batchcreatedatetime"
        t.string   "order"
        t.string   "pudate"
        t.string   "mdbhash"
        t.string   "r"
        t.datetime "created_at"
        t.datetime "updated_at"


      t.timestamps
    end
  end
end
